### ISSUE TITLE
Question about `annotate_beta`

### ISSUE THREAD

**Issue by liangyy** [armartin/prs_disparities#1]
Hi Alicia and Masahiro,

I have a quick question on `annotate_beta` function in `run_prs_holdout.py` here https://github.com/armartin/prs_disparities/blob/323867f54e3cd5e810fdc380e9cc10fddd863afb/run_prs_holdout.py#L21

I am wondering why when `mt.alleles[0] == ss_loc.ref) & (mt.alleles[1] == ss_loc.alt)` and similar conditions meet, the sign of `beta` get flipped. I was thinking that `mt.alleles[0]` is reference allele and `mt.alleles[1]` is alternative allele so that `beta` should not be flipped in the above case. Probably I get it wrong but could you clarify? 

Thanks!

Yanyu

**Comment by mkanai** [comment]
Hi Yanyu,

Thanks for reaching out to us. It seems you are correct: `beta` should not be flipped when `mt.alleles[0] == ss_loc.ref) & (mt.alleles[1] == ss_loc.alt)` but when the other conditions are met. Although we believe this doesn't affect any results in the manuscript (e.g., R2 values etc), we will double-check whether there are any other errors we overlooked.

Thanks so much again for pointing this out.

Best regards,
Masa
